"""Create a single Plane page in the KEIS project that catalogs every
remaining orphan file_asset.

Steps:
  1. Pick up the list of file_assets that are still orphaned after the
     rescue + dedup passes.
  2. Create (or reuse) a page named "Orphan assets catalog" in the
     KEIS project.
  3. Reparent every orphan: set project_id, workspace_id, page_id,
     entity_type=PAGE_DESCRIPTION, entity_identifier=<page_id>. After
     this update the assets are no longer orphaned and can be reached
     through the catalog page.
  4. Render description_html as a sequence of <image-component> blocks
     for images and <a> anchors for everything else.

description_binary is regenerated by gen_binaries_modified.js and
applied in a separate follow-up step so that Live renders the catalog
without merging stale state.
"""
import json
import uuid
from urllib.parse import quote

from django.db import connection


WORKSPACE_SLUG = "keis"
KEIS_PROJECT_ID = "f2669245-b3c5-44b3-9bd6-13c10eaa6b93"
KEIS_WORKSPACE_ID = "9805fa78-211d-4932-971c-df736f703184"
PAGE_TITLE = "Orphan assets catalog"


def main():
    cursor = connection.cursor()

    # 1. Fetch orphans (entity_type + asset attrs).
    cursor.execute("""
        SELECT id::text,
               attributes->>'name' AS name,
               attributes->>'type' AS mime,
               (attributes->>'size')::bigint AS size
        FROM file_assets
        WHERE deleted_at IS NULL AND (
          (entity_type='PAGE_DESCRIPTION' AND page_id IS NULL) OR
          (entity_type='ISSUE_ATTACHMENT' AND issue_id IS NULL) OR
          (entity_type='COMMENT_DESCRIPTION' AND comment_id IS NULL)
        )
        ORDER BY attributes->>'name'
    """)
    orphans = cursor.fetchall()
    print(f"orphans to catalog: {len(orphans)}")

    # 2. Create or reuse the catalog page.
    cursor.execute("""
        SELECT p.id
        FROM pages p
        JOIN project_pages pp ON pp.page_id = p.id AND pp.project_id = %s
        WHERE p.name = %s AND p.deleted_at IS NULL
        LIMIT 1
    """, [KEIS_PROJECT_ID, PAGE_TITLE])
    row = cursor.fetchone()
    if row:
        page_id = str(row[0])
        print(f"reusing existing catalog page: {page_id}")
    else:
        page_id = str(uuid.uuid4())
        cursor.execute("""
            INSERT INTO pages
              (id, name, workspace_id, owned_by_id, access, archived_at, created_at, updated_at,
               description_html, description_binary, description_stripped,
               description_json,
               color, is_locked, view_props, logo_props, is_global, sort_order)
            SELECT %s, %s, %s,
                   (SELECT id FROM users WHERE email='admin@example.com'),
                   0, NULL, NOW(), NOW(),
                   '<p></p>', ''::bytea, '',
                   '{}'::jsonb,
                   '', false, '{}'::jsonb, '{}'::jsonb, false, 65535.0
        """, [page_id, PAGE_TITLE, KEIS_WORKSPACE_ID])
        cursor.execute("""
            INSERT INTO project_pages (id, workspace_id, project_id, page_id, created_at, updated_at)
            VALUES (%s, %s, %s, %s, NOW(), NOW())
        """, [str(uuid.uuid4()), KEIS_WORKSPACE_ID, KEIS_PROJECT_ID, page_id])
        print(f"created catalog page: {page_id}")

    # 3. Reparent every orphan.
    orphan_ids = [aid for aid, _, _, _ in orphans]
    if orphan_ids:
        cursor.execute("""
            UPDATE file_assets
            SET page_id = %s,
                entity_identifier = %s,
                entity_type = 'PAGE_DESCRIPTION',
                project_id = %s,
                workspace_id = %s,
                updated_at = NOW()
            WHERE id::text = ANY(%s)
        """, [page_id, page_id, KEIS_PROJECT_ID, KEIS_WORKSPACE_ID, orphan_ids])
        print(f"reparented {len(orphan_ids)} orphans onto the catalog page")

    # 4. Build description HTML.
    lines = [
        f'<h1 class="editor-heading-block">{PAGE_TITLE}</h1>',
        '<p class="editor-paragraph-block">'
        '移行で親 entity を失ったがユニークなコンテンツを含む file_asset を '
        'このページに集約しています。自動生成。</p>',
        f'<p class="editor-paragraph-block">合計 {len(orphans)} files</p>',
        '<div class="py-4 border-strong-1" data-type="horizontalRule"><div></div></div>',
    ]

    def _escape(s: str) -> str:
        return (
            s.replace("&", "&amp;")
             .replace("<", "&lt;")
             .replace(">", "&gt;")
             .replace('"', "&quot;")
        )

    for aid, name, mime, size in orphans:
        safe_name = _escape(name or "(no name)")
        size_kb = (size or 0) / 1024
        if (mime or "").startswith("image/"):
            # Render inline via the editor's native image-component.
            lines.append(
                f'<h3 class="editor-heading-block">{safe_name} '
                f'<small>({size_kb:.1f} KiB)</small></h3>'
            )
            lines.append(
                f'<image-component id="{aid}" src="{aid}" data-id="{aid}" '
                f'status="uploaded"></image-component>'
            )
        else:
            # Non-images: link to the workspace-scoped asset endpoint.
            href = f"/api/assets/v2/workspaces/{WORKSPACE_SLUG}/{aid}/"
            lines.append(
                f'<p class="editor-paragraph-block">'
                f'<a target="_blank" rel="noopener noreferrer" href="{href}">'
                f'{safe_name}</a> ({size_kb:.1f} KiB)</p>'
            )

    description_html = "".join(lines)

    cursor.execute(
        "UPDATE pages SET description_html = %s, updated_at = NOW() WHERE id = %s",
        [description_html, page_id],
    )
    print(f"description_html size: {len(description_html)} bytes")
    print(f"page_id: {page_id}")

    # Dump modified_pages.jsonl for gen_binaries_modified.js.
    with open("/tmp/catalog_page.jsonl", "w", encoding="utf-8") as f:
        f.write(json.dumps({"id": page_id, "html": description_html}) + "\n")
    print("wrote /tmp/catalog_page.jsonl")


main()
